import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-slate-100 dark:bg-dark-background'>
      <body className={inter.className}>
        <header className='p-4 flex items-center gap-4'>
          <h1 className='p-2'>Pokédex</h1>
          <nav>
            <ul>
              <li>
                <Link href="/">Início</Link>
              </li>
              <li>
                <Link href="/pokemon">Pokemon</Link>
              </li>
              <li>
                <Link href="/">Outros</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className='p-4'>
          {children}
        </div>
      </body>
    </html>
  )
}
